data:
  data_dir: data
  num_classes: 42
  modalities: [ 'audio', 'image', 'text' ]
  include_OOD: False
  samples_per_class: 600

audio:
  audio_csv_path: data/audio/datalist.csv
  audio_train_csv_path: data/audio/datalist_train.csv
  audio_test_csv_path: data/audio/datalist_test.csv
  audio_data_path: data/audio
  audio_features_path: data/audio_features.npy
  diversity:
    compactness: 0
    num_sampling: 10
  sample_noise:
    add_noise_train: False
    add_noise_test: False
    noisy_data_ratio: 0.5
    min_snr: 3
    max_snr: 10
    output_path: data/noisy_audio
  label_switch_prob: 0.5

text:
  text_tsv_path: data/text_data.tsv
  text_test_tsv_path: data/text_data_test.tsv
  text_features_path: data/text_features.npy
  diversity:
    compactness: 0
    num_sampling: 10
  sample_noise:
    add_noise_train: True
    add_noise_test: True
    noisy_data_ratio: 0.5
    noise_config: # https://nlpaug.readthedocs.io/en/latest/
      KeyboardNoise:
        aug_char_min: 1
        aug_char_max: 5
        aug_word_min: 1
        aug_word_max: 3
      SynonymNoise:
        aug_min: 1
        aug_max: 3
  label_switch_prob: 0.5

image:
    image_data_path: data/image_data.pickle
    image_train_path: data/image_data_train.pickle
    image_test_path: data/image_data_test.pickle
#    image_data_path: data/image
    image_features_path: data/image_features.npy
    diversity:
      compactness: 0
      num_sampling: 10
    sample_noise:
        add_noise_train: True
        add_noise_test: True
        noisy_data_ratio: 0.5
        output_path: data/noisy_images.pth
        noise_config:
          gaussian_noise:
            severity: 1
          shot_noise:
              severity: 1
          impulse_noise:
            severity: 1
          defocus_blur:
            severity: 1
          frosted_glass_blur:
            severity: 1
          motion_blur:
            severity: 1
          zoom_blur:
            severity: 1
          snow:
            severity: 1
          frost:
            severity: 1
          fog:
            severity: 1
          brightness:
            severity: 1
          contrast:
            severity: 1
          elastic:
            severity: 1
          pixelate:
            severity: 1
          jpeg_compression:
            severity: 1
    label_switch_prob: 0.5