data:
  data_dir: data
  num_classes: 42
  modalities: [ 'audio', 'image', 'text' ]
  include_OOD: False
  samples_per_class: 600

audio:
  audio_csv_path: data/audio/datalist.csv
  audio_train_csv_path: data/audio/datalist_train.csv
  audio_test_csv_path: data/audio/datalist_test.csv
  audio_data_path: data/audio
  audio_features_path: data/audio_features.npy
  diversity:
    compactness: 0
    num_sampling: 10
  sample_noise:
    add_noise_train: True
    add_noise_test: False
    noisy_data_ratio: 0.5
    min_snr: 3
    max_snr: 10
    output_path: data/noisy_audio_1
  label_switch_prob: 0.2

image:
  path: /path/to/image
  diversity_lambda: 0
  noise_level: 0
  label_switch_prob: 0

text:
  path: /path/to/text
  diversity_lambda: 0
  noise_level: 0
  label_switch_prob: 0


