#!/bin/bash
#SBATCH --job-name=MULTIMODAL_training    # nom du job
#SBATCH --partition=gpu          # choix de la priorité (ici cpu)
#SBATCH --nodes=1                # nombre de noeuds
#SBATCH --ntasks=1               # nombre total de tâches sur tous les nœuds
#SBATCH --cpus-per-task=8        # nombre de coeur cpu par tâche (>1 si tâches multi-threaded)
#SBATCH --gres=gpu:1   
#SBATCH --mem=128G
#SBATCH --time=48:00:00          # le temps total de run (HH:MM:SS)
#SBATCH --output=/home/yanis.gerst/slurm/output_file         # nom du fichier de sortie
#SBATCH --error=/home/yanis.gerst/slurm/error_file          # nom du fichier erreur
#SBATCH --mail-user=yanis.gerst@etu.univ-amu.fr
#SBATCH --mail-type=all     

srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 2
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 2
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 2
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 2
srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 3
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 3
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 3
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 3
srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 4
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 4
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 4
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 4
srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 5
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 5
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 5
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 5
srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 6
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 6
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 6
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 6
srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 7
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 7
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 7
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 7
srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 8
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 8
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 8
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 8
srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 9
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 9
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 9
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 9
srun python run_baselines.py -a 50 -m image -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 10
srun python run_baselines.py -a 50 -m audio -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 10
srun python run_baselines.py -a 50 -m text -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 10
srun python run_baselines.py -a 50 -m multimodal -activation exp -cm 10 -lr 0.001 -e 70 --mode train --id 10